language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 7.2
    - 7.3

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source

script:
    - ./vendor/bin/phpcs --standard=PSR2 ./src ./tests
    - travis_retry  ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
